### ISSUE TITLE
initiallize weights for CNN

### ISSUE THREAD

**Issue by vignesh10** [google/prettytensor#13]
Thanks for the making TF simple :)
I am just curious as to how I can pre-initialize the weights before performing any operations. 

Thanks in advance!

**Comment by eiderman** [comment]
The weights can be initialized by creating an OP using
tf.initialize_all_variables() and then calling run on the result. Note:
each time you call initialize_all_variables,  it adds graph nodes.

A word of caution: The simple local runner that is provided by PT will
automatically initialize the variables when you call run if any have been
added, so be careful when interleaving creation and that utility or make
sure to pass on the flag to disable creation.

I'm answering from my phone, so some names may be slightly wrong.

**Comment by eiderman** [comment]
Please reopen if I didn't answer the question well enough.
