### ISSUE TITLE
tf.nn.conv2d_transpose is not exist in PrettyTensor

### ISSUE THREAD

**Issue by codertimo** [google/prettytensor#31]
I need to make Deconvolution Network Layer.
Now I'm working with PT, how can I add deconvolution layer.
Please make some conv2d_transpose() API :)

**Comment by eiderman** [comment]
Pretty Tensor lets you register your own methods.  The simplest way is just
to decorate a method with `@pt.Register` and then the PrettyTensor object
will be passed in as the first item and all relevant variable and name
scopes will be set.

```python
@pt.Register
def conv2d_transpose(input_pt, out_channels, output_shape, strides,
padding='SAME', name=None):
  # Note that name will default to conv2d_transpose when not set.
  height = input_pt.get_shape()[1]
  width= input_pt.get_shape()[2]
  in_channels= input_pt.get_shape()[3]

  filter = tf.get_variable('weights', initializer=tf.
truncated_normal_initializer(), shape=[height, width, output_channels,
in_channels], dtype=tf.float32)

  # Note: The returned value will automatically be wrapped as a pretty
tensor object.
  return tf.nn.conv2d_transpose(input_pt, filter,
output_shape=output_shape, stride=stride, padding=padding, name=name)
```

Of course to fully spec this out, it would require better initializer
settings and input sanity checking, but this should be close to a complete
setup (note: I'm away from my desk, so the syntax is written from memory
and might have a few things out of place).

Feel free to create a pull request if you fully flesh it out.

**Comment by codertimo** [comment]
Wow Thank you 👍 

I have extra question. How can I apply conv2d_transpose(deconv2d) in the sequential mode.
like using conv2d in sequential mode.

```
# def deconv2d(input_pt, output_channels, output_shape, strides,padding='SAME', name=None):
#-> TO Sequantial Mode Function

net.conv2d(3,64)  //kernel size, output_channel
net.deconv2d(output_shape) //kernal size, output_channel
```

**Comment by eiderman** [comment]
You should get sequential mode for free when you register the function.
Did you have any trouble with that?
