### ISSUE TITLE
optimizer not an argument of apply_optimizer

### ISSUE THREAD

**Issue by atabakd** [google/prettytensor#33]
[Here](https://github.com/google/prettytensor/blob/master/docs/pretty_tensor_top_level.md#apply_optimizerlosses-regularizetrue-include_markedtrue), optimizer is not in arguments of apply_optimizer

**Comment by eiderman** [comment]
Thanks for the bug. That is an error with the script that generates the
documentation, but the first arg is indeed optimizer.  I will look at
fixing the generation script.

Thanks!
