### ISSUE TITLE
evaluate_model does not take an average?

### ISSUE THREAD

**Issue by gngdb** [google/prettytensor#35]
Reading the code, it looks like the `evaluate_model` method [here][eval] doesn't take an average over all of the minibatches that it evaluates. It calls `run_model`, which iterates over minibatches and gets the loss functions by calling `sess.run` [here][run]. This variable is then just reassigned on the next minibatch (although it might be printed or saved when `_log_and_save` is called). Then, once we've iterated over all minibatches the _most recent_ `results` [is returned][return]. In `evaluate_model` this is just indexed to output whatever loss function we wanted to evaluate over the test set.

There's no point in iterating over the whole test set if we're not taking an average when we run `evaluate_model`.

[return]: https://github.com/google/prettytensor/blob/master/prettytensor/local_trainer.py#L302
[run]: https://github.com/google/prettytensor/blob/master/prettytensor/local_trainer.py#L281-L286
[eval]: https://github.com/google/prettytensor/blob/master/prettytensor/local_trainer.py#L344-L386

**Comment by eiderman** [comment]
This is intentional with the built in modes.  You can compute an average across batches by building the accuracy ops with pt.Phase.infer. This will compute an average inside the graph by leveraging LOCAL_VARIABLES.

Sorry for the sparseness of the docs and the late reply.
