### ISSUE TITLE
Cannot find tensorflow upon installation

### ISSUE THREAD

**Issue by renmengye** [google/prettytensor#36]
I have tensorflow 10.0 installed but installing prettytensor throws the following error:

Could not find any downloads that satisfy the requirement tensorflow>=0.9.0rc0

**Comment by eiderman** [comment]
Thanks for the bug, v0.12 I just uploaded a new version that should work with the latest version. I'm disappointed that it seems to be sorting lexigraphically instead of numerically for version numbers.
