### ISSUE TITLE
PrettyTensor breaks GPU-installation of TensorFlow

### ISSUE THREAD

**Issue by Hvass-Labs** [google/prettytensor#40]
Installing PrettyTensor seems to have broken my GPU installation of TensorFlow. After installing PrettyTensor it would use the CPU version of TensorFlow.

I'm using a conda env named `tf-gpu` for the GPU version and another env named `tf` for the CPU version.

Here's the output of the pip install:

	(tf-gpu) magnus@torpedo:~/development/TensorFlow-Tutorials$ pip install prettytensor
	Collecting prettytensor
	  Downloading prettytensor-0.7.1-py3-none-any.whl (273kB)
	    100% |████████████████████████████████| 276kB 1.1MB/s 
	Collecting enum34>=1.0.0 (from prettytensor)
	  Downloading enum34-1.1.6-py3-none-any.whl
	Requirement already satisfied: six>=1.10.0 in /home/magnus/anaconda3/envs/tf-gpu/lib/python3.5/site-packages (from prettytensor)
	Collecting tensorflow>=0.12.0rc0 (from prettytensor)
	  Using cached tensorflow-0.12.0rc1-cp35-cp35m-manylinux1_x86_64.whl
	Requirement already satisfied: numpy>=1.11.0 in /home/magnus/anaconda3/envs/tf-gpu/lib/python3.5/site-packages (from tensorflow>=0.12.0rc0->prettytensor)
	Requirement already satisfied: protobuf==3.1.0 in /home/magnus/anaconda3/envs/tf-gpu/lib/python3.5/site-packages (from tensorflow>=0.12.0rc0->prettytensor)
	Requirement already satisfied: wheel>=0.26 in /home/magnus/anaconda3/envs/tf-gpu/lib/python3.5/site-packages (from tensorflow>=0.12.0rc0->prettytensor)
	Requirement already satisfied: setuptools in /home/magnus/anaconda3/envs/tf-gpu/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg (from protobuf==3.1.0->tensorflow>=0.12.0rc0->prettytensor)
	Installing collected packages: enum34, tensorflow, prettytensor
	Successfully installed enum34-1.1.6 prettytensor-0.7.1 tensorflow-0.12.0rc1

The culprit seems to be this:

    Collecting tensorflow>=0.12.0rc0 (from prettytensor)
      Using cached tensorflow-0.12.0rc1-cp35-cp35m-manylinux1_x86_64.whl

I tried `pip uninstall tensorflow` and then `pip install tensorflow_gpu-0.12.0rc0-cp35-cp35m-linux_x86_64.whl` but it doesn't work because it says it is already installed:

	(tf-gpu) magnus@torpedo:~/Downloads$ pip install tensorflow_gpu-0.12.0rc0-cp35-cp35m-linux_x86_64.whl 
	Requirement already satisfied: tensorflow-gpu==0.12.0rc0 from file:///home/magnus/Downloads/tensorflow_gpu-0.12.0rc0-cp35-cp35m-linux_x86_64.whl in /home/magnus/anaconda3/envs/tf-gpu/lib/python3.5/site-packages
	Requirement already satisfied: six>=1.10.0 in /home/magnus/anaconda3/envs/tf-gpu/lib/python3.5/site-packages (from tensorflow-gpu==0.12.0rc0)
	Requirement already satisfied: protobuf==3.1.0 in /home/magnus/anaconda3/envs/tf-gpu/lib/python3.5/site-packages (from tensorflow-gpu==0.12.0rc0)
	Requirement already satisfied: wheel>=0.26 in /home/magnus/anaconda3/envs/tf-gpu/lib/python3.5/site-packages (from tensorflow-gpu==0.12.0rc0)
	Requirement already satisfied: numpy>=1.11.0 in /home/magnus/anaconda3/envs/tf-gpu/lib/python3.5/site-packages (from tensorflow-gpu==0.12.0rc0)
	Requirement already satisfied: setuptools in /home/magnus/anaconda3/envs/tf-gpu/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg (from protobuf==3.1.0->tensorflow-gpu==0.12.0rc0)

How do I fix this, please?

**Comment by eiderman** [comment]
I just did an upload that removes the setup.py hard dependency on TF so that it doesn't flag tensorflow-gpu.  I don't have a GPU handy to test at the moment, so please let me know if that helps; otherwise I will test it when I get to a reasonable computer.

**Comment by Hvass-Labs** [comment]
Thanks very much for the rapid response, I greatly appreciate that!

I'm currently in the process of getting Linux working on a new PC with a fast GPU. It has been a nightmare and I've spent several days on it so far, trying different distros, window managers, etc. Earlier today I had a chance to try your update to PrettyTensor and it seemed to work, but something else was broken with my installation. It seems that the best thing is to run pure Ubuntu. I strongly dislike the Unity interface but everything else that I've tried has been worse somehow.

I'll let you know when I have tested PrettyTensor properly, I just didn't want to leave you hanging now that you answered so promptly.

**Comment by Hvass-Labs** [comment]
It works now. I think your solution is correct. PrettyTensor should not automatically install TensorFlow.

**Comment by Baali2015** [comment]
I'm a newbie and trying to install prettytensor using Anaconda envs as

(C:\Users\.........\Anaconda3) C:\>conda install prettytensor
Fetching package metadata .............

PackageNotFoundError: Packages missing in current channels:

  - prettytensor

We have searched for the packages in the following channels:

  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch

Can any help me with this problem? I use CPU-tensorflow on window 10 platform
