### ISSUE TITLE
weights reuse in {gru, lstm}_cell/_sequence methods

### ISSUE THREAD

**Issue by AdrianLsk** [google/prettytensor#49]
Hi all,

First of all thanks for a great library.

Now, looking at the code for the rnn methods, the weights are always created anew with every call of {gru, lstm}_cell method, is that correct? If so, shouldn't the weights be created only once and reused at each timestep?

**Comment by eiderman** [comment]
The weights are reused when using sequence_lstm and sequence_gru by
entering a variable scope with reuse set to true (behind pretty tensor
templates, which was an overcomplicated design and it's use is discouraged).

**Comment by AdrianLsk** [comment]
Sorry, I didn't quite catch it. 

So say I want to use a for loop, with lstm_cell without creating new weights at each step, therefore I have to pass weights argument to the cell method.

Or is it enough to use the variable scope with the reuse flag (even for 0th time step) with a correct name?If so, what's the scope name pattern that I have to use in order to get the variables initialized correctly? Because I have tried it but I am getting an error corresponding to PreconditionFailed, since the scope I am using is not correct.

Many thanks.
