### ISSUE TITLE
Branching

### ISSUE THREAD

**Issue by nishithbsk** [google/prettytensor#8]
Hi,

Thanks for a great library!

Is there a way I could send a single input to multiple towers without splitting/dividing the input and not have them join at the end?

Thanks!

**Comment by eiderman** [comment]
So multiple towers is a little overloaded, so I will answer it for 2 senses (pardon slight variance in syntax, I'm doing this from memory):

Do you mean:
a) a different tower for each GPU? If so, I recommend using variable_scope to create 2 copies of the graph with tied parameters.

def build_my_graph(...)
  ...

tower_builder = tf.make_template(tower, build_my_graph)
with tf.device("gpu:0"):
  tower1 = tower_builder()
with tf.device("gpu:1"):
  tower2 = tower_builder()

b) sending an input to multiple towers with different parameters:

If you aren't using sequential, then the handle to the layer is immutable and you just grab it:
x = input.fully_connected(...)
branch1 = x.fully_connected(...)
branch2 = x.fully_connected(...)

In the case of sequential, you can get an immutable copy by calling "as_layer()" (this name is perhaps less than ideal) and then optionally make that sequential:

seq = input.sequential()
seq.fully_connected(...)

branch1 = seq.as_layer().sequential()
branch2 = seq.as_layer().sequential()

**Comment by nishithbsk** [comment]
Thank you so much! I was looking for (b).
